### ISSUE TITLE
maven

### ISSUE THREAD

**Issue by lolaclinton** [pishen/sbt-emr-spark#10]
I looked on the maven repo and can't find this but I saw the Spark Deployer. How do you want people to use this?

**Comment by pishen** [comment]
@lolaclinton SBT plugins are published to Bintray but not Maven Central. You can find the jars here
https://dl.bintray.com/sbt/sbt-plugin-releases/net.pishen/sbt-emr-spark/scala_2.10/sbt_0.13/
By adding the following line to your `project-folder/project/plugins.sbt` (note that there's a `project` sub-folder in the path), SBT should find and download the library from Bintray automatically.
```
addSbtPlugin("net.pishen" % "sbt-emr-spark" % "0.10.0")
```
Please let me know if you meet any other problems. : )

**Comment by lolaclinton** [comment]
Thanks! I'll give it a try :)
