### ISSUE TITLE
2.11

### ISSUE THREAD

**Issue by lolaclinton** [pishen/sbt-emr-spark#12]
On the page you write

Add sbt-emr-spark in project/plugins.sbt
addSbtPlugin("net.pishen" % "sbt-emr-spark" % "0.10.0")
Prepare your build.sbt
name := "sbt-emr-spark-test"

scalaVersion := "2.11.11"

But you only have it compiled for Scala 2.10 on https://dl.bintray.com/sbt/sbt-plugin-releases/net.pishen/sbt-emr-spark/scala_2.10/sbt_0.13/

**Comment by pishen** [comment]
@lolaclinton The Scala version of SBT plugin has nothing to do with the Scala version of your project. If you use SBT 0.13.x, it uses Scala 2.10.x for its plugin system.

**Comment by lolaclinton** [comment]
How are you setting up the resolver? I tried this but it didn't take.

resolvers += Resolver.bintrayRepo("sbt", "sbt-plugin-releases")

**Comment by pishen** [comment]
@lolaclinton You don't need to add the resolver, sbt-plugin-release should be available by default. Could you paste your SBT error message here?

**Comment by lolaclinton** [comment]
I think it was my screwup. I put the plugin in the build.sbt :(

**Comment by pishen** [comment]
I'm closing this first, feel free to re-open it if you have any other questions.
