### ISSUE TITLE
Cannot see cluster listed on AWS elasticmapreduce

### ISSUE THREAD

**Issue by pmminov** [pishen/sbt-emr-spark#24]
I'm sorry if this obvious. After running sparkCreateCluster I can see a box up on EC2 dashboard, sparkListClusters reports the cluster is there and I can submit jobs...

but if you go to /elasticmapreduce dashboard is not there.... Do I have a wrong expectation here? would be nice to have some more documentation on how it looks/results on AWS

**Comment by pishen** [comment]
Have you try https://github.com/pishen/sbt-emr-spark/issues/20#issuecomment-334349503 ?

**Comment by pmminov** [comment]
yup, solution described there

sparkRunJobFlowRequest := sparkRunJobFlowRequest.value.withVisibleToAllUsers(true)

did the trick, worth putting a note on the README

thank you for your quick response

**Comment by pishen** [comment]
`withVisibleToAllUsers` is now set to `true` by default.
