### ISSUE TITLE
Would be nice to expose some decorators in settings

### ISSUE THREAD

**Issue by alexmnyc** [pishen/sbt-emr-spark#8]
For example, I need to add withEc2KeyName so that I can get onto the cluster. It would be nice to have a generic way of adding additional config attributes via some decorators similar to:

extraJobFlowInstancesConfig := {
  (jobFlow:JobFlowInstancesConfig) => jobFlow.withEc2KeyName("MyKeyName") 
}

**Comment by pishen** [comment]
Tried to fix this in version 0.8.0, which expose the underlying AWS objects for you to modify the settings.
Please refer to https://github.com/pishen/sbt-emr-spark/tree/0.8.0#modify-the-configurations-of-underlying-aws-objects for more details.
